# PREFIX DEF
COMMAND_LINE = "CL"
WORK_MAN = "WM"

# dispatcher suffix
DISPATCHER_SUFFIX="Dispatcher"

WM_DEBUG="TRUE"

WM_PARAM_TYPE = 'TYPE'

WM_PARAM_SUB_TYPE= 'SUB_TYPE'

WM_PARAM_WORK= 'WORK'

WM_PARAM_CONFIG_FILE= 'CONFIG_FILE'

WM_PARAM_EXT_PY_DIR='EXT_PY_DIR'

def get_dispatcher_suffix():
	return DISPATCHER_SUFFIX